# Generated by Django 4.1.7 on 2023-12-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
