# Generated by Django 4.1.7 on 2023-12-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_created_at_product_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
