# Generated by Django 4.1.7 on 2023-12-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
