# Generated by Django 4.1.7 on 2023-12-05 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_id_number', message='請輸入有效的身分證號碼', regex='^[A-Z][1-2]\\d{8}$')]),
        ),
    ]
