# Generated by Django 4.1.7 on 2023-12-07 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_store_name_product_unique_store_item'),
        ('user', '0007_alter_user_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='name',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product_name',
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_purchases', to='product.product'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_purchases', to='user.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='purchases',
            field=models.ManyToManyField(blank=True, related_name='name', to='user.purchase'),
        ),
    ]
