# Generated by Django 4.1.7 on 2023-12-07 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_store_unique_store_name'),
        ('user', '0008_remove_purchase_name_remove_purchase_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='store_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='store_purchases', to='store.store'),
        ),
    ]
